## Fathia Nuq Qamarina
## 2009106012
## A1 20
# Posttest 4

#### Import Package dan membaca dataset

In [90]:
import pandas as pd
import numpy as np

df = pd.read_csv('Employee.csv')
df.head()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No   
1  Bachelors         2013       Pune            1   28  Female          No   
2  Bachelors         2014  New Delhi            3   38  Female          No   
3    Masters         2016  Bangalore            3   27    Male          No   
4    Masters         2017       Pune            3   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64 
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64 
 4   Age                        4653 non-null   int64 
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64 
 8   LeaveOrNot                 4653 non-null   int64 
dtypes: int64(5), object(4)
memory usage: 327.3+ KB


# Data Preprocessing

#### 1. Bagi dataset menjadi training set dan testing set dengan proporsi 70:30

In [92]:
X = df.iloc[:,:-1] # Target
y = df.iloc[:,-1] # Feature

In [93]:
#melakukan split data train dan data test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [94]:
#melihat baris dan kolom tiap dataset
print("Dimensi X_train : ", x_train.shape)
print("Dimensi X_train : ", x_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test  : ", y_test.shape)

Dimensi X_train :  (3257, 8)
Dimensi X_test :  (1396, 8)
Dimensi y_train :  (3257,)
Dimensi y_test  :  (1396,)


In [95]:
#melakukan penyimpanan data
x_train.to_csv("Data_x_train.csv", index=False)
x_test.to_csv("Data_x_test.csv", index=False)
y_train.to_csv("Data_y_train.csv", index=False)
y_test.to_csv("Data_y_test.csv", index=False)


#### 2. Lakukan normalisasi data pada salah satu attribute menggunakan Min Max scaler (buatlah copy dataset terlebih dahulu)

In [96]:
#membuat copy dataset
cp_dataset = df[[ 'JoiningYear', 'PaymentTier', 'Age', 'ExperienceInCurrentDomain' ]]

print("Nilai Data Sebelum scaling : ")
print(cp_dataset)

print("Nilai standar deviasi: ", np.std(cp_dataset))

Nilai Data Sebelum scaling : 
      JoiningYear  PaymentTier  Age  ExperienceInCurrentDomain
0            2017            3   34                          0
1            2013            1   28                          3
2            2014            3   38                          2
3            2016            3   27                          5
4            2017            3   24                          2
...           ...          ...  ...                        ...
4648         2013            3   26                          4
4649         2013            2   37                          2
4650         2018            3   27                          5
4651         2012            3   30                          2
4652         2015            3   33                          4

[4653 rows x 4 columns]
Nilai standar deviasi:  JoiningYear                  1.863177
PaymentTier                  0.561375
Age                          4.825568
ExperienceInCurrentDomain    1.558073
dtype: float6

In [97]:
#melakukan normalisasi data
from sklearn.preprocessing import MinMaxScaler

MinMaxScaler = MinMaxScaler()
Scaled_data = MinMaxScaler.fit_transform(cp_dataset)

print("Nilai Data setelah scaling : ")
print(Scaled_data)
print("\n Nilai standar deviasi: ", np.std(Scaled_data))

Nilai Data setelah scaling : 
[[0.83333333 1.         0.63157895 0.        ]
 [0.16666667 0.         0.31578947 0.42857143]
 [0.33333333 1.         0.84210526 0.28571429]
 ...
 [1.         1.         0.26315789 0.71428571]
 [0.         1.         0.42105263 0.28571429]
 [0.5        1.         0.57894737 0.57142857]]

 Nilai standar deviasi:  0.3255976786718249


#### 3. Lakukan standarisasi pada dataset (buatlah copy dataset terlebih dahulu)

In [98]:
#membuat copy dataset
cp_dataset = df[[ 'JoiningYear', 'PaymentTier', 'Age', 'ExperienceInCurrentDomain' ]]

print("Nilai Data Sebelum scaling : ")
print(copy_dataset)

print("Nilai standar deviasi: ", np.std(cp_dataset))

Nilai Data Sebelum scaling : 
      JoiningYear  PaymentTier  Age  ExperienceInCurrentDomain
0            2017            3   34                          0
1            2013            1   28                          3
2            2014            3   38                          2
3            2016            3   27                          5
4            2017            3   24                          2
...           ...          ...  ...                        ...
4648         2013            3   26                          4
4649         2013            2   37                          2
4650         2018            3   27                          5
4651         2012            3   30                          2
4652         2015            3   33                          4

[4653 rows x 4 columns]
Nilai standar deviasi:  JoiningYear                  1.863177
PaymentTier                  0.561375
Age                          4.825568
ExperienceInCurrentDomain    1.558073
dtype: float6

In [99]:
#membuat standarisasi dataset
from sklearn.preprocessing import StandardScaler

StandardScaler = StandardScaler()
Scaled_data = StandardScaler.fit_transform(copy_dataset)

print("Nilai Data setelah scaling : ")
print(Scaled_data)
print("\n Nilai standar deviasi: ", np.std(Scaled_data))

Nilai Data setelah scaling : 
[[ 1.03963837  0.53750299  0.95464513 -1.86490139]
 [-1.10723275 -3.0251771  -0.28873172  0.06055412]
 [-0.57051497  0.53750299  1.78356303 -0.58126438]
 ...
 [ 1.57635615  0.53750299 -0.49596119  1.34419112]
 [-1.64395053  0.53750299  0.12572723 -0.58126438]
 [-0.03379719  0.53750299  0.74741565  0.70237262]]

 Nilai standar deviasi:  1.0


#### 4. Lakukan Data cleaning pada data dengan nilai null (jika tidak ada nilai null pada dataset, maka buatlah menjadi ada). Ganti nilai null sesuai ketentuan. (bilangan bulat : median/modus, bilangan desimal : mean, tulisan : modus).

In [100]:
#melihat pada dataset apakah terdapat nilai null
print ("Record data dengan nilai null :")
print(df.isna().sum())

Record data dengan nilai null :
Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64


- pada dataset tidak terdapat nilai null, maka akan dibuat nilai null pada dataset

In [101]:
#membuat nilai null
df.iloc[2,4] = np.nan
df.iloc[3,3] = np.nan
df.head()

Education  JoiningYear       City  PaymentTier   Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore          3.0  34.0    Male          No   
1  Bachelors         2013       Pune          1.0  28.0  Female          No   
2  Bachelors         2014  New Delhi          3.0   NaN  Female          No   
3    Masters         2016  Bangalore          NaN  27.0    Male          No   
4    Masters         2017       Pune          3.0  24.0    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [102]:
#data sudah terdapat null
print ("Record data dengan nilai null :")
print(df.isna().sum())

tipeData_pay = df.dtypes['PaymentTier']
print("\nTipe data atribut PaymentTier: ")
print(tipeData_pay)

tipeData_age = df.dtypes['Age']
print("\nTipe data atribut Age")
print(tipeData_age)

Record data dengan nilai null :
Education                    0
JoiningYear                  0
City                         0
PaymentTier                  1
Age                          1
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64

Tipe data atribut PaymentTier: 
float64

Tipe data atribut Age
float64


- Karena tipe data yang memiliki nilai null adalah float/desimal maka penggantian null menggunakan stategy mean

In [103]:
#menangani nilai null
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df[["PaymentTier","Age"]] = imputer.fit_transform(df[["PaymentTier","Age"]])

print("\nJumlah null setelah menggunakan SimpleImputer: ")
print(df.isna().sum())


Jumlah null setelah menggunakan SimpleImputer: 
Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64


#### 5. Lakukan Data cleaning pada data dengan nilai duplikat. (Jika tidak ada nilai duplikat pada dataset, maka buatlah menjadi ada)

In [104]:
#melihat dataset apakah terdapat nilai duplikat
print ("Record data dengan nilai duplikat :")
print(df.duplicated().sum())
df[df.duplicated()]

Record data dengan nilai duplikat :
1889


Education  JoiningYear       City  PaymentTier   Age  Gender  \
111   Bachelors         2017       Pune          2.0  27.0  Female   
130   Bachelors         2017  Bangalore          3.0  26.0  Female   
138   Bachelors         2017  New Delhi          3.0  28.0    Male   
160   Bachelors         2014  Bangalore          3.0  28.0  Female   
167   Bachelors         2014  Bangalore          3.0  25.0    Male   
...         ...          ...        ...          ...   ...     ...   
4640  Bachelors         2015  Bangalore          3.0  35.0    Male   
4642  Bachelors         2012  Bangalore          3.0  36.0  Female   
4646  Bachelors         2013  Bangalore          3.0  25.0  Female   
4648  Bachelors         2013  Bangalore          3.0  26.0  Female   
4652  Bachelors         2015  Bangalore          3.0  33.0    Male   

     EverBenched  ExperienceInCurrentDomain  LeaveOrNot  
111           No                          5           1  
130           No                          4           0  
138           No                          2           0  
160           No                          3           0  
167           No                          3           0  
...          ...                        ...         ...  
4640          No                          0           0  
4642          No                          4           0  
4646          No                          3           0  
4648          No                          4           0  
4652         Yes                          4           0  

[1889 rows x 9 columns]

In [105]:
#menghapus nilai nilai duplikat pada dataset
df.drop_duplicates(inplace=True)
print("Setelah Data Duplikat dihapus :", df.duplicated().sum())

Setelah Data Duplikat dihapus : 0


#### 6. Ganti tipe data salah satu attribute angka

In [106]:
print("Tipe data sebelum :", df.dtypes['Age'])
df['Age'] = df['Age'].astype('int64')
print("Tipe data sesudah :", df.dtypes['Age'])

Tipe data sebelum : float64
Tipe data sesudah : int64


In [107]:
df.head()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore     3.000000   34    Male          No   
1  Bachelors         2013       Pune     1.000000   28  Female          No   
2  Bachelors         2014  New Delhi     3.000000   29  Female          No   
3    Masters         2016  Bangalore     2.698194   27    Male          No   
4    Masters         2017       Pune     3.000000   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

#### 7. Lakukan one hot encoding pada dataset yang kalian miliki.

In [108]:
from sklearn.preprocessing import OneHotEncoder
df.head()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore     3.000000   34    Male          No   
1  Bachelors         2013       Pune     1.000000   28  Female          No   
2  Bachelors         2014  New Delhi     3.000000   29  Female          No   
3    Masters         2016  Bangalore     2.698194   27    Male          No   
4    Masters         2017       Pune     3.000000   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [109]:
#melakukan encoding pada atribut EverBenched
encoder = OneHotEncoder(sparse=False)
EverBenched_Encoder = encoder.fit_transform(df[["EverBenched"]])
EvBench = pd.DataFrame(EverBenched_Encoder)

df = df.join(EvBench)
df.head()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore     3.000000   34    Male          No   
1  Bachelors         2013       Pune     1.000000   28  Female          No   
2  Bachelors         2014  New Delhi     3.000000   29  Female          No   
3    Masters         2016  Bangalore     2.698194   27    Male          No   
4    Masters         2017       Pune     3.000000   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot    0    1  
0                          0           0  1.0  0.0  
1                          3           1  1.0  0.0  
2                          2           0  1.0  0.0  
3                          5           1  1.0  0.0  
4                          2           1  0.0  1.0

In [110]:
#merename nama atribut setelah melakukan encoding
df = df.rename(columns={
    0 : 'EverBenched_No',
    1 : 'EverBenched_Yes'
})
df.head()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore     3.000000   34    Male          No   
1  Bachelors         2013       Pune     1.000000   28  Female          No   
2  Bachelors         2014  New Delhi     3.000000   29  Female          No   
3    Masters         2016  Bangalore     2.698194   27    Male          No   
4    Masters         2017       Pune     3.000000   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  EverBenched_No  EverBenched_Yes  
0                          0           0             1.0              0.0  
1                          3           1             1.0              0.0  
2                          2           0             1.0              0.0  
3                          5           1             1.0              0.0  
4                          2           1             0.0              1.0

In [111]:
df.to_csv("Data_Employee_baru.csv", index=False)